blog/urls.py
from django.urls import path
from .views import PostDetail, PostList, add_comment

urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('<slug:slug>', PostDetail.as_view(), name='single'),
    # path('post/<slug:slug>', PostDetail.as_view(), name='single'),
    path('addcomment/', add_comment, name='addcomment'),
]

sprofile/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from .views import index

urlpatterns = [
    path('', index, name='index'),
    path('about', TemplateView.as_view(template_name='about.html', extra_context={'page_title':'About'}), name='about'),
    path('send-cv', TemplateView.as_view(template_name='send-cv.html', extra_context={'page_title':'CV'}), name='send-cv'),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    icon = models.ImageField(upload_to='uploads/blog', blank=True)
    description =  models.TextField()
    is_active = models.BooleanField(default=True)
    created_date = models.DateField(auto_now=False, auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.name

class PostQueryset(models.query.QuerySet):
    def publish(self):
        return self.filter(status='publish', category__is_active=True)

class PostManager(models.Manager):
    def get_queryset(self):
        return PostQueryset(self.model, using=self._db)

    def publish(self):
        return self.get_queryset().publish()


class Post(models.Model):
    STATUS_POST = (
        ('draft', 'Draft'),
        ('publish', 'Publish')
        )
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='category')
    image = models.ImageField(upload_to='uploads/blog', blank=True)
    content = models.TextField()
    status = models.CharField(max_length=100, blank=False, choices=STATUS_POST, default='publish')
    seo_keywords = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    created_date = models.DateField(auto_now=False, auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True, auto_now_add=False)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:single", kwargs={'slug': self.slug})

    def get_comment_count(self):
        return Comment.objects.filter(post__id = self.id, status='publish').count()


class Comment(models.Model):
    STATUS_COMMENT = (
        ('spam', 'Spam'),
        ('publish', 'Publish')
        )
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post')
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=150)
    body = models.TextField()
    created_date = models.DateField(auto_now=False, auto_now_add=True)
    status = models.CharField(max_length=100, blank=False, choices=STATUS_COMMENT, default='publish')

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
        'name',
        'email',
        'body'
        ]

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Post, Category, Comment
from .forms import CommentForm
from django.contrib import messages


class PostList(ListView):
    queryset = Post.objects.publish()
    context_data = {
        'category': Category.objects.filter(is_active=True),
    }
    extra_context = {
        'page_title':'Blog',
    }

class PostDetail(DetailView, FormMixin):
    model = Post
    form_class = CommentForm
    slug_field = 'slug'
    slug_url_kwarg = 'slug'
    extra_context = {
        'page_title':'Blog',
    }

    def get_context_data(self, *args, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        comment = Comment.objects.select_related('post') \
            .filter(post__slug=self.kwargs.get('slug'), status='publish')
        context['comments'] = comment
        context['comment_form'] = CommentForm
        return context
    

def add_comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST or None)
        if form.is_valid:
            post = Post.objects.filter(pk=int(request.POST.get('post_id'))).first()
            form.instance.post = post
            form.save()
            messages.success(request, '*** Form submission successful ***')
    return HttpResponseRedirect("{}#comment".format(reverse('blog:single', kwargs={'slug':post.slug})))

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}

{% with post=object %}
{% endwith %}

{% block content %}
    <a href="{% url 'blog:list' %}">&lt; Blog List</a>
    <h2  style="text-decoration:underline">{{post.title}}</h2>
     <small>{{post.created_date}} - {{post.category.name}}, by : {{post.user.username}}</small>
     <br>
     <img src="{{ post.image.url }}" alt="alt-image" style="margin:1rem 0; width:100%">

     <section>
         <p>
            {{post.content|safe}}
         </p>
     </section>
     <br/>
     <section>
         <h2 style="text-decoration:underline">Comment</h2>

            {% if comments.count == 0 %}
                <em>No Comment Yet</em>
            {% endif %}

                {% for comment in comments %}
                    <label><strong>{{comment.name}}</strong> - <em>{{comment.email}}</em></label>
                    <p>
                        {{comment.body}}
                    </p>
                {% endfor %}
        <p>----------------------------------------------------------------------------</p>
            {% if messages %}
                <ul class="list">
                    {% for message in messages %}
                    <li{% if message.tags %} class="text-blue"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
         <form method="POST" action="{% url 'blog:addcomment' %}" id="comment">
             {% csrf_token %}
             <input type="hidden" name="post_id" value="{{post.id}}">
             <input type="hidden" name="post_slug" value="{{post.slug }}">
             {{comment_form.as_p}}
             <button>Add Comment</button>
         </form>
     </section>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <h2 style="margin-bottom:2rem;">Blog</h2>
    <ul class="list">
    {% for post in object_list  %}
        <li style="display:block">
            <h4>{{post.title}} - <a href="{{ post.get_absolute_url }}">link</a></h4>
            <small>{{post.created_date}} - {{post.category.name}}, by : {{post.user.username}} - comment : {{post.get_comment_count}}</small>
        </li>
    {%endfor%}
    </ul>
{% endblock content %}