blog/urls.py
from django.urls import path
from .views import PostDetail, PostList, add_comment

urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('<slug:slug>', PostDetail.as_view(), name='single'),
    # path('post/<slug:slug>', PostDetail.as_view(), name='single'),
    path('addcomment/', add_comment, name='addcomment'),
]

contact/urls.py
from django.urls import path
from .views import add_contact

urlpatterns = [
    path('add', add_contact, name='add')
]

sprofile/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from .views import index

urlpatterns = [
    path('', index, name='index'),
    path('about', TemplateView.as_view(template_name='about.html', extra_context={'page_title':'About'}), name='about'),
    path('send-cv', TemplateView.as_view(template_name='send-cv.html', extra_context={'page_title':'CV'}), name='send-cv'),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

send_cv/models.py
from django.db import models

# Create your models here.

class EmailTemplate(models.Model):
    title = models.CharField(max_length=255)
    template = models.TextField()

class History(models.Model):
    email = models.EmailField()
    created_date = models.DateField(auto_now_add=True)

send_cv/views.py
from django.shortcuts import render

# Create your views here.

templates/about.html
{% extends "base.html" %}
{% block content %}
<section>
    <h2>Sprovvile</h2>
    <h4>Simple Personal Web with Django</h4>

    <p>
        Source code : <a href="https://github.com/fwazdi02/sprovvile">github</a>
    </p>
</section>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{{ request.site.icon.url }}">
    <title>{{ page_title }} - {{ request.site.site }}</title>
    <style type="text/css">
        body {
            font-size: 16px;
            text-align: center;
        }

        .post{
            text-align: left;
        }
        
        img.avatar{
            border-radius: 20rem;
        }

        section{
            margin-bottom: 1rem;
        }

        #portfolio figure{
            width: 45%;
            display: inline-block;
            margin: 0;
            margin-bottom: 1rem;
        }

        figure > img {
            width: 50%;
            height: auto;
        }

        main.main-wrapper{
            width: 50%;
            margin-right: auto;
            margin-left: auto;
        }

        ul.list{
            margin: 0 0 1.5rem 0;
            padding: 0;
        }
        ul.list li{
            display: inline-block;
            list-style: none;
        }

        ul.list li a{
            margin: .2rem .5rem;
        }

        .text-blue{
            color: blue;
        }

        @media screen and (max-width:764px){
        #portfolio figure{
            width: 98%;
            display: inline-block;
            margin: 0;
            margin-bottom: 1rem;
        }

        main.main-wrapper{
            width: 100%;
            margin-right: auto;
            margin-left: auto;
        }

        }

    </style>
</head>
<body>
<nav>
    <ul class="list">
        {# <li><strong><em>{-{{ request.site.site}}-}</em></strong></li> #}
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'blog:list' %}">Blog</a></li>
        <li><a href="{% url 'send-cv' %}">My CV</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
    </ul>
</nav>
<main class="main-wrapper">

    {% block content %}

    {% endblock content %}
     <br/>
    <p>----------------------------------------------------------------------------</p>
    <footer class="footer">
        <h3>{{ request.site.site }}</h3>
        <p>{{request.site.myprofile.address}} - {{request.site.myprofile.city}}</p>
        <p>{{request.site.myprofile.phone_number}}</p>
        <p>{{request.site.myprofile.user.email}}</p>

        <ul class="list">
            <li><a href="{{request.site.myprofile.facebook}}">fb</a></li>
            <li><a href="{{request.site.myprofile.twitter}}">tw</a></li>
            <li><a href="{{request.site.myprofile.instagram}}">ig</a></li>
            <li><a href="{{request.site.myprofile.pinterest}}">pin</a></li>
            <li><a href="{{request.site.myprofile.github}}">gth</a></li>
            <li><a href="{{request.site.myprofile.gitlab}}">gtl</a></li>
        </ul>
    </footer>

</main>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <section>
        <img src="{{ request.site.myprofile.avatar.url }}" class="avatar">
        <h3>About Me</h3 
        <div>
            <p>{{ request.site.myprofile.about_me }}</p>
        </div>
    </section>    

    <section>
        <h3>My Skills</h3> 
        <div>
            {% for skill in myskill %}
            <p>{{ skill.title }} : {{ skill.presentase }} / {{ skill.max_presentase }}</p>
            <small>{{ skill.description }}</small>
            {% endfor %}
        </div>
    </section>    

    <section>
        <h3>My Portfolio</h3> 
        <div id="portfolio">
            {% for portfolio in myportfolio %}
            <figure>
                <img src="{{ portfolio.image.url }}">    
                <figcaption>
                    <p>{{ portfolio.title }}</p>
                    <small><a href="{{ portfolio.ext_link }}">link</a> ~ {{ portfolio.start_date }} ::: {{ portfolio.end_date }}</small>
                    <p>
                        <small>{{ portfolio.description }}</small>
                    </p>
                </figcaption>
            </figure>
            {% endfor %}
        </div>
    </section>


    <section id="contact">
        <h3>Contact</h3>
        <div>
            {% if messages %}
            <ul class="list">
                {% for message in messages %}
                <li{% if message.tags %} class="text-blue"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form method="POST" action="{% url 'contact:add' %}">
                {% csrf_token %}
                {{ contact_form.as_p }}
                <button>Send</button>
            </form>
        </div>
    </section>

{% endblock content %}

templates/send-cv.html
{% extends "base.html" %}
{% block content %}
<h2>Hello There,</h2>
<br>
<p>
    Download My CV : <a href="{{ request.site.myprofile.cv.url }}">link</a>
    <br>
</p>
{% endblock content %}